# Generated by Django 5.2 on 2025-04-22 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diameter', models.FloatField(help_text='Diameter in inches')),
                ('length', models.FloatField(help_text='Length in feet')),
                ('quantity', models.IntegerField(default=0)),
                ('import_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='warehouse_images/')),
            ],
        ),
    ]
