# Generated by Django 5.2 on 2025-04-22 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPipeCountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='history/original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='history/processed/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_history', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Water Pipe Count History',
                'verbose_name_plural': 'Water Pipe Count History Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
